### ISSUE TITLE
nodejs8.10 lambda is deprecated

### ISSUE THREAD

**Issue by yzhanggithub** [turnerlabs/terraform-ecs-fargate#41]
Deprecation of creating nodejs8.10 lambda is Jan 6, 2020 and updating is Feb 3, 2020.
https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

It was a simple lambda and we just need to update the runtime in ecs-event-stream.tf file. I tested in an app bootstrapped from fargate-create.

I did a PR for terraform-ecs-fargate-nlb (python3 and nodejs10.x), not sure if that's the right repo. There are a few fargate repos which contain logz lambdas and a nodejs8.10 lambda, are the files kept in sync in some way or are they updated separately?

**Comment by jritsema** [comment]
Thanks for the [PR](https://github.com/turnerlabs/terraform-ecs-fargate-nlb/pull/11).  Yes, would you mind replicating for this repo as well?  Also, ideally it's separated into two different PRs.  One for the logzio change and the other for the dashboard node version.  Thanks!
