### ISSUE TITLE
Node 10 Lambda phase 1 support ends by July 30, 2021

### ISSUE THREAD

**Issue by yzhanggithub** [turnerlabs/terraform-ecs-fargate#64]
There is a Node 10 lambda in the repo. It may cause issue to create (or update later) when Node 10 Lambda support ends in AWS.
Workaround if not updated in the release: 
In env/dev/ecs-event-stream.tf, change the runtime to either value - "nodejs12.x" or "nodejs14.x"

**Comment by jritsema** [comment]
This can be closed.

**Comment by awlawl** [comment]
The template is now using 14.x 

Thanks
